### ISSUE TITLE
Erro 500 ao buscar cliente com id inexistente

### ISSUE THREAD

**Issue by oliveiralex** [rafaelrok/clients#1]
Olá Rafael, meu nome é Alexandre e estou corrigindo sua atividade.

Trabalho aceito, parabéns! Para ficar 100%, sugiro incluir o tratamento de exceções. Está retornando erro 500 quando o id não existe. Tanto para a busca do cliente por id (GET), ao atualizar um cliente (UPDATE) e excluí-lo (DELETE).

Abraço e bons estudos

**Comment by rafaelrok** [comment]
Boa noite Alexandre,
Efetuei a implementação desculpa havia esquecido, commit "exception handling".
Obrigado!
